content:
  - name: posts
    label: Posts
    type: collection
    path: _posts   # not _posts
    view:
      fields: [title, body]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }