media:
  input: public/assets
  output: /assets

content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    slug: "{{slug}}"
    view:
      fields: [ title, body ]  # Only show title and body in the list view
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }