content:
  - name: posts
    label: Posts
    type: collection
    path: _posts   # not _posts
    view:
      fields: [title, body]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
backend:
  name: github
  repo: BioInfoCommunity/nextjs-blog-2
  branch: es   # this is where PagesCMS will commit
  pull_request: true   # optional if supported by your version