title: My Site
description: A simple Jekyll + GitHub Pages site
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
