<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ page.title }} | {{ site.title }}</title>

  <!-- EMBL VF CSS -->
  <link rel="stylesheet" href="https://assets.emblstatic.net/vf/v2.5.25/css/styles.css">
</head>
<body>
  <header>
    <h1>{{ site.title }}</h1>
    <nav>
      <a href="{{ '/' | relative_url }}">Inicio</a>
      <a href="{{ '/about/' | relative_url }}">Acerca</a>
    </nav>
  </header>

  <main>
    <div class="vf-content">
      <div class="vf-grid">
        <div><p>side bar</p></div>
        <div>{{ content }}</div>
      </div>
    </div>
  </main>

  <footer>
    <p>&copy; {{ site.time | date: '%Y' }} {{ site.title }}</p>
  </footer>
</body>
<!-- JS -->
  <script src="https://assets.emblstatic.net/vf/v2.5.25/scripts/scripts.js"></script>
</html>
