<html lang="en" dir="ltr">

<head>
	<meta charset="utf-8" />
	<title>AlphaFold | EMBL-EBI Training</title>
	<link rel="stylesheet" href="https://assets.emblstatic.net/vf/v2.5.25/css/styles.css" type="text/css">

	<link rel="stylesheet" href="https://ebi.emblstatic.net/web_guidelines/EBI-Icon-fonts/v1.3/fonts.css" type="text/css"
		media="all" />
</head>
<body class="vf-body">
	<div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas>
		<span data-protection-message-disable="true"></span>
		<header id="masthead-black-bar" class="clearfix masthead-black-bar | ebi-header-footer vf-content vf-u-fullbleed">
		</header>
		<div class="layout-container">
			<main class="page-content clearfix" role="main">
				<div class="visually-hidden">
					<a id="main-content" tabindex="-1">
					</a>
				</div>
				<div class="vf-content">
					<div>
						<div id="block-ebi-academy-content--89">
							<div id="ebi-hero-background" style="">
								<div class="vf-body">
									<section class="vf-hero | vf-u-fullbleed" style="background:none;">
										<div class="vf-hero__content | vf-box | vf-stack vf-stack--400" style="min-width:350px">
											<p class="vf-hero__kicker" style="text-transform:uppercase">Online tutorial</p>
											<h2 id="course_title" class="vf-hero__heading">AlphaFold</h2>
											<p class="vf-hero__subheading">A practical guide</p>
										</div>
									</section>
								</div>
							</div>
							<article data-history-node-id="2555" role="article">
								<div data-history-node-id="2555" role="article">
									<div class="vf-body published">
										<div class="vf-u-margin__top--500"></div>
										<section class="embl-grid">
											<div class="embl-training__sidebar">
												<div class="vf-u-margin__top--500"></div>
												<figure class="vf-figure ebi-academy-book-cover-image">

													<img class="vf-figure__image"
														src="//trainingcontent.embl.org/sites/default/files/book-images/AlphaFold.png" alt="">

												</figure>
												<a
													href="https://www.ebi.ac.uk/training/online/courses/alphafold/an-introductory-guide-to-its-strengths-and-limitations">
													<button style="width:80%" class="vf-button vf-button--primary vf-button--sm">Enter
														course</button>
												</a>
												<div class="vf-u-margin__top--400"></div>
												<div id="favourite_parent" class="vf-u-margin__top--200"></div>
												<button class="vf-bookmark vf-bookmark--inline | vf-button vf-button--link"
													style="margin:0; padding:0">

													<span class="vf-bookmark--icon vf-bookmark--icon-heart">
														<svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 140 140"
															height="140" width="140">
															<g transform="matrix(10,0,0,10,0,0)">
																<path d="M7,12.45l-5.52-5c-3-3,1.41-8.76,5.52-4.1,4.11-4.66,8.5,1.12,5.52,4.1Z"></path>
															</g>
														</svg>
													</span>Mark as favourite
													<img id="progress_img" alt="progress"
														src="http://trainingcontent.embl.org/themes/custom/ebi_academy/images/progressbar.gif"
														style="width: 20px; height: 20px;" width="15" height="15">
												</button>
												<div class="vf-u-margin__top--400"></div>
												<div id="progress_bar_div" style="display:none">
													<label id="progress_bar_label" for="progress_bar">Course progress:</label>
													<progress id="progress_bar" style="width:100%; height:10px; margin-top: 5px" value="0"
														max="100">
														0%
													</progress>
												</div>
												<div class="vf-u-margin__top--500"></div>
												<p class="vf-u-type__text-body--3 vf-u-margin--0">
													Time to complete: </p>
												<p class="vf-u-type__text-body--3 vf-u-margin--0">3 hours</p>
												</p>

												<div class="vf-u-margin__top--500"></div>
												<p class="vf-u-type__text-body--3 vf-u-margin--0 vf-u-margin__bottom-md">
													This course includes:</p>

												<div class="vf-u-margin__top--200"></div>
												<ul class="vf-list vf-list--compact vf-u-margin__bottom-md">
													<li class="vf-list__item vf-u-margin--0">
														<span class="ebiacademy-icon vf-u-type__text-body--3 vf-u-margin--0">
															<i class="icon icon-common icon-pencil-alt content-type-icon"></i>
															<strong>Activities</strong>
														</span>
													</li>
													<li class="vf-list__item vf-u-margin--0">
														<span class="ebiacademy-icon vf-u-type__text-body--3 vf-u-margin--0">
															<i class="icon icon-common icon-tasks content-type-icon"></i>
															<strong>Quizzes</strong>
														</span>
													</li>
													<li class="vf-list__item vf-u-margin--0">
														<span class="ebiacademy-icon vf-u-type__text-body--3 vf-u-margin--0">
															<i class="icon icon-common icon-video content-type-icon"></i>
															<strong>Videos</strong>
														</span>
													</li>
												</ul>
												<hr class="vf-divider vf-u-margin__bottom-md">
												<p class="vf-u-type__text-body--3 vf-u-margin--0 vf-u-margin__bottom--xs">
													Written by:</p>
												<div class="vf-u-margin__top--100"></div>
												<ul class="vf-list vf-list--compact vf-u-margin__bottom-md">
													<li class="vf-list__item ">
														<a class="vf-link vf-link--primary vf-u-type__text-body--3 "
															href=https://www.ebi.ac.uk/people/person/paulyna-gabriela-magana-gomez> Paulyna Gabriela
															Magana Gomez </a>
													</li>
													<li class="vf-list__item ">
														<a class="vf-link vf-link--primary vf-u-type__text-body--3 "
															href=https://www.ebi.ac.uk/training/trainers/oleg-kovalevskiy> Oleg Kovalevskiy </a>
													</li>
												</ul>
												<p class="vf-u-type__text-body--3 vf-u-margin--0 vf-u-margin__bottom-md">
													Last reviewed:
												<p class="vf-u-type__text-body--3 vf-u-margin--0">June 2025</p>
												</p>
												<div class="vf-u-margin__top--500"></div>
												<hr class="vf-divider vf-u-margin__bottom-md">
												<p>
													<a href="https://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons"
															src="http://trainingcontent.embl.org/themes/custom/ebi_academy/images/CC_BY.png"
															style="width: 125px; height: 44px;" width="125" height="44"></a>
												</p>
												<p class="vf-u-type__text-body--3">All materials are free cultural works licensed under a
													Creative
													Commons
													<a href="https://creativecommons.org/licenses/by/4.0/"
														class="vf-link vf-link--primary  vf-u-margin--0" style="display:inline">Attribution 4.0
														International (CC BY 4.0) license</a>, except where further licensing details are provided.
												</p>
												<div class="vf-u-margin__top--500"></div>
												<hr class="vf-divider vf-u-margin__bottom-md">
											</div>
											<!-- Sidebar end -->
											<div class="acc">
												<div class="vf-u-margin__top--500"></div>
												{{ content }}


											</div>
										</section>
									</div>
								</div>
							</article>



						</div>
					</div>
				</div>
			</main>
  <script src="https://assets.emblstatic.net/vf/v2.5.25/scripts/scripts.js"></script>
		</div>

	</div>

</body>

</html>
